---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: C# Publish
description: 'Publishes a C# project to GitHub Packages.'
author: 'Ismo Vuorinen'

branding:
  icon: package
  color: blue

inputs:
  dotnet-version:
    description: 'Version of .NET SDK to use.'
    required: false
  namespace:
    description: 'GitHub namespace for the package.'
    required: true
    default: 'ivuorinen'
  token:
    description: 'GitHub token with package write permissions'
    required: false

outputs:
  publish_status:
    description: 'Overall publish status (success/failure)'
    value: ${{ steps.set-status.outputs.status }}
  package_version:
    description: 'Version of the published package'
    value: ${{ steps.extract-version.outputs.version }}
  package_url:
    description: 'URL of the published package'
    value: ${{ steps.publish-package.outputs.package_url }}

runs:
  using: composite
  steps:
    - name: Validate Inputs
      id: validate
      shell: bash
      run: |
        set -euo pipefail

        # Validate .NET version format if provided
        if [[ -n "${{ inputs.dotnet-version }}" ]]; then
          if ! [[ "${{ inputs.dotnet-version }}" =~ ^[0-9]+(\.[0-9]+(\.[0-9]+)?)?(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
            echo "::error::Invalid dotnet-version format: '${{ inputs.dotnet-version }}'. Expected formats: X, X.Y, X.Y.Z, or with optional prerelease (e.g., 8, 7.0, 8.0.100, 7.0.0-rc.1)"
            exit 1
          fi
        fi

        # Validate namespace format (GitHub username/org name)
        if ! [[ "${{ inputs.namespace }}" =~ ^[a-zA-Z0-9]([a-zA-Z0-9]|-(?=[a-zA-Z0-9])){0,38}$ ]]; then
          echo "::error::Invalid namespace format: '${{ inputs.namespace }}'. Must be a valid GitHub username/organization name (1-39 characters, alphanumeric and hyphens, no leading/trailing hyphens)"
          exit 1
        fi

        # Validate GitHub token format (basic validation)
        if [[ -n "${{ inputs.token }}" ]]; then
          if ! [[ "${{ inputs.token }}" =~ ^gh[efpousr]_[a-zA-Z0-9]{36}$ ]]; then
            echo "::warning::GitHub token format may be invalid. Expected format: gh*_36characters or gho_36characters"
          fi
        fi

    - name: Detect .NET SDK Version
      id: detect-dotnet-version
      uses: ivuorinen/actions/dotnet-version-detect@main
      with:
        default-version: '7.0'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
      with:
        dotnet-version: ${{ inputs.dotnet-version || steps.detect-dotnet-version.outputs.dotnet-version }}

    - name: Cache NuGet packages
      id: cache-nuget
      uses: ivuorinen/actions/common-cache@main
      with:
        type: 'nuget'
        paths: '~/.nuget/packages'
        key-files: '**/*.csproj,**/*.props,**/*.targets'
        key-prefix: 'csharp-publish'

    - name: Restore Dependencies
      shell: bash
      run: |
        set -euo pipefail

        # Always run dotnet restore to ensure project.assets.json is present
        if [[ "${{ steps.cache-nuget.outputs.cache-hit }}" == 'true' ]]; then
          echo "Cache hit - running fast dotnet restore"
        fi
        dotnet restore

    - name: Build Solution
      shell: bash
      run: |
        set -euo pipefail

        dotnet build --configuration Release --no-restore

    - name: Pack Solution
      shell: bash
      run: |
        set -euo pipefail

        dotnet pack --configuration Release --no-build --no-restore --output ./artifacts

    - name: Extract Package Version
      id: extract-version
      shell: bash
      run: |
        set -euo pipefail

        # Find the newest .nupkg file by modification time and extract version
        PACKAGE_FILE=$(find ./artifacts -name "*.nupkg" -type f -printf '%T@ %p\n' | sort -rn | head -n 1 | cut -d' ' -f2-)
        if [ -n "$PACKAGE_FILE" ]; then
          # Extract version from filename (assumes standard naming: PackageName.Version.nupkg)
          VERSION=$(basename "$PACKAGE_FILE" .nupkg | sed 's/.*\.\([0-9]\+\.[0-9]\+\.[0-9]\+.*\)$/\1/')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "package_file=$PACKAGE_FILE" >> "$GITHUB_OUTPUT"
        else
          echo "version=unknown" >> "$GITHUB_OUTPUT"
          echo "package_file=" >> "$GITHUB_OUTPUT"
        fi

    - name: Publish Package
      id: publish-package
      shell: bash
      env:
        API_KEY: ${{ inputs.token || github.token }}
      run: |
        set -euo pipefail

        PACKAGE_URL="https://github.com/${{ inputs.namespace }}/packages/nuget"
        echo "package_url=$PACKAGE_URL" >> $GITHUB_OUTPUT

        # First attempt
        if ! dotnet nuget push ./artifacts/*.nupkg \
          --api-key "$API_KEY" \
          --source "https://nuget.pkg.github.com/${{ inputs.namespace }}/index.json" \
          --skip-duplicate \
          --no-symbols; then

          echo "::warning::First publish attempt failed, retrying after 5 seconds..."
          sleep 5

          dotnet nuget push ./artifacts/*.nupkg \
            --api-key "$API_KEY" \
            --source "https://nuget.pkg.github.com/${{ inputs.namespace }}/index.json" \
            --skip-duplicate \
            --no-symbols
        fi

    - name: Set publish status output
      if: always()
      id: set-status
      shell: bash
      run: |-
        echo "status=${{ steps.publish-package.outcome == 'success' && 'success' || 'failure' }}" >> $GITHUB_OUTPUT
