---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PHP Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:
    push:
      branches:
        - main
        - master
    pull_request:
      branches:
        - main
        - master

jobs:
  tests:
    name: PHP Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set Git Config
        uses: ivuorinen/actions/composite-set-git-config@main

      - name: Composer Install
        uses: ivuorinen/actions/composite-php-composer@main

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --verbose
