---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Dotnet Version Detect
description: 'Detects .NET SDK version from global.json or defaults to a specified version.'
author: 'Ismo Vuorinen'

branding:
  icon: code
  color: blue

inputs:
  default-version:
    description: 'Default .NET SDK version to use if global.json is not found.'
    required: true
    default: '7.0'

outputs:
  dotnet-version:
    description: 'Detected or default .NET SDK version.'
    value: ${{ steps.parse-version.outputs.detected-version }}

runs:
  using: composite
  steps:
    - name: Parse .NET Version
      id: parse-version
      uses: ivuorinen/actions/version-file-parser@main
      with:
        language: 'dotnet'
        tool-versions-key: 'dotnet'
        dockerfile-image: 'dotnet'
        validation-regex: '^[0-9]+\.[0-9]+(\.[0-9]+)?$'
        default-version: ${{ inputs.default-version }}
