#!/bin/sh
set -eu

if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi

INPUT=$(cat)
CLEAN_INPUT=$(printf '%s' "$INPUT" | LC_ALL=C tr -d '\000-\010\013\014\016-\037')
FILE_PATH=$(printf '%s' "$CLEAN_INPUT" | jq -r '.tool_input.file_path // .tool_input.filePath // empty' 2>/dev/null || true)

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

case "$FILE_PATH" in
*/README.md)
  # Only block if a sibling action.yml exists (meaning this README is auto-generated)
  DIR=$(dirname "$FILE_PATH")
  if [ -f "$DIR/action.yml" ] || [ -f "$DIR/action.yaml" ]; then
    echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"Action READMEs are auto-generated by action-docs. Run make docs instead of editing directly."}}'
  fi
  ;;
esac
