#!/bin/sh
set -eu

if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.filePath // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

case "$FILE_PATH" in
# Allow these specific READMEs
*/README.md)
  # Get the directory depth — action READMEs are at depth 1 (e.g., docker-build/README.md)
  # Allow: ./README.md, ./_tests/README.md, ./validate-inputs/docs/*, ./.github/*
  case "$FILE_PATH" in
  ./README.md | README.md) exit 0 ;;
  */_tests/* | */.github/* | */validate-inputs/docs/* | */docs/*) exit 0 ;;
  *)
    echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"Action READMEs are auto-generated by action-docs. Run make docs instead of editing directly."}}'
    ;;
  esac
  ;;
esac
