---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Python Lint and Fix
description: 'Lints and fixes Python files, commits changes, and uploads SARIF report.'
author: 'Ismo Vuorinen'

branding:
  icon: 'code'
  color: 'yellow'

runs:
  using: composite

  steps:
    - name: Check for Python Files
      shell: bash
      run: |
        if ! find . -name "*.py" | grep -q .; then
          echo "No Python files found. Skipping lint and fix."
          exit 0
        fi

    - name: Install flake8 and autopep8
      shell: bash
      run: |
        pip install flake8 autopep8

    - name: Run flake8
      shell: bash
      run: |
        flake8 --format=sarif --output-file=flake8.sarif

    - name: autopep8 Fix
      shell: bash
      run: |
        autopep8 --in-place --recursive .

    - name: Set Git Config for Fixes
      uses: ivuorinen/actions/composite-set-git-config@main

    - name: Commit Fixes
      shell: bash
      run: |
        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add .
          git commit -m "fix: applied python lint fixes"
          git pull --rebase
          git push || {
            echo "Push failed. Fetching latest changes..."
            git fetch
            git rebase origin/$(git branch --show-current)
            git push
          }
        fi

    - name: Upload SARIF Report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: flake8.sarif
