# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# permissions:
#   - contents: write  # Required for committing and pushing formatting fixes
---
name: Prettier Fix
description: Run Prettier to fix code style violations
author: 'Ismo Vuorinen'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for authentication'
    required: false
    default: ${{ github.token }}
  username:
    description: 'GitHub username for commits'
    required: false
    default: 'github-actions'
  email:
    description: 'GitHub email for commits'
    required: false
    default: 'github-actions@github.com'
  max-retries:
    description: 'Maximum number of retry attempts for npm install operations'
    required: false
    default: '3'

outputs:
  files_changed:
    description: 'Number of files changed by Prettier'
    value: ${{ steps.format.outputs.files_changed }}
  format_status:
    description: 'Formatting status (success/failure)'
    value: ${{ steps.format.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Validate Inputs
      id: validate
      uses: ivuorinen/actions/validate-inputs@0fa9a68f07a1260b321f814202658a6089a43d42
      with:
        action-type: 'prettier-fix'
        token: ${{ inputs.token }}
        email: ${{ inputs.email }}
        username: ${{ inputs.username }}
        max-retries: ${{ inputs.max-retries }}

    - name: Checkout Repository
      uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v6-beta
      with:
        token: ${{ inputs.token }}

    - name: Node Setup
      id: node-setup
      uses: ivuorinen/actions/node-setup@0fa9a68f07a1260b321f814202658a6089a43d42

    - name: Cache npm Dependencies
      id: cache-npm
      uses: ivuorinen/actions/common-cache@0fa9a68f07a1260b321f814202658a6089a43d42
      with:
        type: 'npm'
        paths: 'node_modules'
        key-files: 'package-lock.json,yarn.lock,pnpm-lock.yaml,bun.lockb'
        key-prefix: 'prettier-fix-${{ steps.node-setup.outputs.package-manager }}'

    - name: Install Dependencies
      id: install-deps
      if: steps.cache-npm.outputs.cache-hit != 'true'
      shell: sh
      env:
        PACKAGE_MANAGER: ${{ steps.node-setup.outputs.package-manager }}
      run: |
        set -eu

        echo "Installing dependencies using $PACKAGE_MANAGER..."

        # Package managers have built-in retry logic
        case "$PACKAGE_MANAGER" in
          "pnpm")
            pnpm install --frozen-lockfile
            ;;
          "yarn")
            if [ -f ".yarnrc.yml" ]; then
              yarn install --immutable
            else
              yarn install --frozen-lockfile
            fi
            ;;
          "bun")
            bun install --frozen-lockfile
            ;;
          "npm"|*)
            npm ci
            ;;
        esac

        echo "✅ Dependencies installed successfully"

    - name: Run Prettier Fix
      id: format
      shell: sh
      env:
        PACKAGE_MANAGER: ${{ steps.node-setup.outputs.package-manager }}
      run: |
        set -eu

        package_manager="$PACKAGE_MANAGER"

        echo "Running Prettier fix with $package_manager..."

        # Count files before fix
        files_before=$(git status --porcelain | wc -l || echo "0")

        # Run Prettier fix based on package manager
        case "$package_manager" in
          "pnpm")
            pnpm exec prettier --write .
            ;;
          "yarn")
            yarn prettier --write .
            ;;
          "bun")
            bunx prettier --write .
            ;;
          "npm"|*)
            npx prettier --write .
            ;;
        esac

        # Count files after fix
        files_after=$(git status --porcelain | wc -l || echo "0")

        # Calculate absolute difference and set status
        delta=$((files_after - files_before))
        files_changed=$((delta < 0 ? -delta : delta))  # Ensure non-negative
        status=$([ "$files_changed" -eq 0 ] && echo success || echo failure)

        printf '%s\n' "files_changed=$files_changed" >> "$GITHUB_OUTPUT"
        printf '%s\n' "status=$status" >> "$GITHUB_OUTPUT"

        echo "✅ Prettier fix completed. Files changed: $files_changed, Status: $status"

    - name: Push Fixes
      if: always()
      uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
      with:
        commit_message: 'style: autofix Prettier violations'
        commit_user_name: ${{ inputs.username }}
        commit_user_email: ${{ inputs.email }}
        add_options: '-u'
