---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Prettier Fix

on:
  workflow_dispatch:

jobs:
  prettier-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git Config
        uses: ivuorinen/actions/composite/set-git-config@main

      - name: Node Setup
        uses: ivuorinen/actions/composite/node-setup@main

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Prettier Fix
        run: |
          npx prettier --write .

      - name: Push Fixes
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: autofix Prettier violations"
          add_options: "-u"
