[extend]
useDefault = true

[allowlist]
description = "Allowlisted files"
paths = [
    '''node_modules''',
    '''.git''',
    '''dist''',
    '''yarn.lock''',
    '''package-lock.json''',
    '''pnpm-lock.yaml''',
    '''_tests'''
]
