---
build_rules:
  - id: allow-scripts-package-json
    pattern: package.json
    confidence: HIGH
    severity: WARNING
    message: 'Check scripts in package.json'

scan_rules:
  - id: js-eval
    pattern: eval\(
    type: regex
    confidence: HIGH
    severity: WARNING
    message: 'Avoid using eval()'

  - id: js-secrets
    pattern: (password|secret|token|key).*=.*['"][^'"]*['"]
    type: regex
    confidence: HIGH
    severity: WARNING
    message: 'Possible hardcoded secret'
