---
doublestar: true
gitignore_excludes: true
formatter:
  basic:
    include_document_start: true
    retain_line_breaks: true
    scan_folded_as_literal: false
    max_line_length: 0
    indentless_arrays: true
include:
  - '**/action.yml'
  - '**/action.yaml'
  - .github/workflows/*.yml
  - .github/workflows/*.yaml
exclude:
  - node_modules
