---
extends: default

ignore: |
  node_modules/
  .worktrees/

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  trailing-spaces:
    level: warning
