---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Prettier Check
description: 'Run Prettier check on the repository with advanced configuration and reporting'
author: Ismo Vuorinen

branding:
  icon: check-circle
  color: green

inputs:
  working-directory:
    description: 'Directory containing files to check'
    required: false
    default: '.'
  prettier-version:
    description: 'Prettier version to use'
    required: false
    default: 'latest'
  config-file:
    description: 'Path to Prettier config file'
    required: false
    default: '.prettierrc'
  ignore-file:
    description: 'Path to Prettier ignore file'
    required: false
    default: '.prettierignore'
  file-pattern:
    description: 'Files to include (glob pattern)'
    required: false
    default: '**/*.{js,jsx,ts,tsx,css,scss,json,md,yaml,yml}'
  cache:
    description: 'Enable Prettier caching'
    required: false
    default: 'true'
  fail-on-error:
    description: 'Fail workflow if issues are found'
    required: false
    default: 'true'
  report-format:
    description: 'Output format (json, sarif)'
    required: false
    default: 'sarif'
  max-retries:
    description: 'Maximum number of retry attempts'
    required: false
    default: '3'
  plugins:
    description: 'Comma-separated list of Prettier plugins to install'
    required: false
    default: ''
  check-only:
    description: 'Only check for formatting issues without fixing'
    required: false
    default: 'true'

outputs:
  files-checked:
    description: 'Number of files checked'
    value: ${{ steps.check.outputs.files_checked }}
  unformatted-files:
    description: 'Number of files with formatting issues'
    value: ${{ steps.check.outputs.unformatted_files }}
  sarif-file:
    description: 'Path to SARIF report file'
    value: ${{ steps.check.outputs.sarif_file }}
  cache-hit:
    description: 'Indicates if there was a cache hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Validate Inputs
      id: validate
      shell: bash
      run: |
        set -euo pipefail

        # Validate working directory
        if [ ! -d "${{ inputs.working-directory }}" ]; then
          echo "::error::Invalid working-directory: '${{ inputs.working-directory }}'. Directory does not exist"
          exit 1
        fi

        # Validate path security (prevent path traversal)
        if [[ "${{ inputs.working-directory }}" == *".."* ]]; then
          echo "::error::Invalid working-directory: '${{ inputs.working-directory }}'. Path traversal not allowed"
          exit 1
        fi

        # Validate prettier version format
        if [[ "${{ inputs.prettier-version }}" != "latest" ]]; then
          if ! [[ "${{ inputs.prettier-version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?$ ]]; then
            echo "::error::Invalid prettier-version: '${{ inputs.prettier-version }}'. Expected semantic version (e.g., 3.0.0) or 'latest'"
            exit 1
          fi
        fi

        # Validate config file path security
        if [[ "${{ inputs.config-file }}" == *".."* ]] || [[ "${{ inputs.config-file }}" == "/"* ]]; then
          echo "::error::Invalid config-file path: '${{ inputs.config-file }}'. Path traversal not allowed"
          exit 1
        fi

        # Validate ignore file path security
        if [[ "${{ inputs.ignore-file }}" == *".."* ]] || [[ "${{ inputs.ignore-file }}" == "/"* ]]; then
          echo "::error::Invalid ignore-file path: '${{ inputs.ignore-file }}'. Path traversal not allowed"
          exit 1
        fi

        # Validate file pattern format (basic safety check)
        if [[ "${{ inputs.file-pattern }}" == *".."* ]] || [[ "${{ inputs.file-pattern }}" == "/"* ]]; then
          echo "::error::Invalid file-pattern: '${{ inputs.file-pattern }}'. Absolute paths and path traversal not allowed"
          exit 1
        fi

        # Validate boolean inputs
        case "${{ inputs.cache }}" in
          true|false) ;;
          *)
            echo "::error::Invalid cache value: '${{ inputs.cache }}'. Expected: true or false"
            exit 1
            ;;
        esac

        case "${{ inputs.fail-on-error }}" in
          true|false) ;;
          *)
            echo "::error::Invalid fail-on-error value: '${{ inputs.fail-on-error }}'. Expected: true or false"
            exit 1
            ;;
        esac

        case "${{ inputs.check-only }}" in
          true|false) ;;
          *)
            echo "::error::Invalid check-only value: '${{ inputs.check-only }}'. Expected: true or false"
            exit 1
            ;;
        esac

        # Validate report format
        case "${{ inputs.report-format }}" in
          json|sarif) ;;
          *)
            echo "::error::Invalid report-format: '${{ inputs.report-format }}'. Expected: json or sarif"
            exit 1
            ;;
        esac

        # Validate max-retries (positive integer)
        if ! [[ "${{ inputs.max-retries }}" =~ ^[0-9]+$ ]] || [ "${{ inputs.max-retries }}" -le 0 ]; then
          echo "::error::Invalid max-retries: '${{ inputs.max-retries }}'. Must be a positive integer"
          exit 1
        fi

        # Validate max-retries range
        if [ "${{ inputs.max-retries }}" -gt 10 ]; then
          echo "::error::Invalid max-retries: '${{ inputs.max-retries }}'. Maximum allowed is 10"
          exit 1
        fi

        # Validate plugins format if provided
        if [ -n "${{ inputs.plugins }}" ]; then
          # Check for basic npm package name format and prevent command injection
          if ! [[ "${{ inputs.plugins }}" =~ ^[a-zA-Z0-9@/._,-]+$ ]]; then
            echo "::error::Invalid plugins format: '${{ inputs.plugins }}'. Use comma-separated npm package names (e.g., plugin1,@scope/plugin2)"
            exit 1
          fi

          # Check for suspicious patterns
          if [[ "${{ inputs.plugins }}" == *";"* ]] || [[ "${{ inputs.plugins }}" == *"&&"* ]] || [[ "${{ inputs.plugins }}" == *"|"* ]]; then
            echo "::error::Invalid plugins format: '${{ inputs.plugins }}'. Command injection patterns not allowed"
            exit 1
          fi
        fi

    - name: Setup Node.js
      uses: ivuorinen/actions/node-setup@main

    - name: Set up Cache
      id: cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: inputs.cache == 'true'
      with:
        path: |
          node_modules/.cache/prettier
          .prettier-cache
        key: ${{ runner.os }}-prettier-${{ hashFiles('**/package.json', '**/package-lock.json', '${{ inputs.config-file }}') }}
        restore-keys: |
          ${{ runner.os }}-prettier-

    - name: Install Dependencies
      shell: bash
      run: |
        set -euo pipefail

        cd ${{ inputs.working-directory }}

        # Function to install with retries
        install_with_retries() {
          local attempt=1
          local max_attempts=${{ inputs.max-retries }}

          while [ $attempt -le $max_attempts ]; do
            echo "Installation attempt $attempt of $max_attempts"

            # Install Prettier and base dependencies
            if npm install \
              prettier@${{ inputs.prettier-version }} \
              @prettier/plugin-xml \
              prettier-plugin-packagejson \
              prettier-plugin-sh; then

              # Install additional plugins if specified
              if [ -n "${{ inputs.plugins }}" ]; then
                IFS=',' read -ra PLUGINS <<< "${{ inputs.plugins }}"
                for plugin in "${PLUGINS[@]}"; do
                  if ! npm install "$plugin"; then
                    return 1
                  fi
                done
              fi

              return 0
            fi

            attempt=$((attempt + 1))
            if [ $attempt -le $max_attempts ]; then
              echo "Installation failed, waiting 10 seconds before retry..."
              sleep 10
            fi
          done

          echo "::error::Failed to install dependencies after $max_attempts attempts"
          return 1
        }

        install_with_retries

    - name: Prepare Configuration
      id: config
      shell: bash
      run: |
        set -euo pipefail

        cd ${{ inputs.working-directory }}

        # Create default config if none exists
        if [ ! -f "${{ inputs.config-file }}" ]; then
          echo "Creating default Prettier configuration..."
          cat > "${{ inputs.config-file }}" <<EOF
        {
          "semi": true,
          "singleQuote": true,
          "tabWidth": 2,
          "useTabs": false,
          "trailingComma": "es5",
          "printWidth": 100,
          "arrowParens": "avoid",
          "endOfLine": "lf"
        }
        EOF
        fi

        # Create default ignore file if none exists
        if [ ! -f "${{ inputs.ignore-file }}" ]; then
          echo "Creating default Prettier ignore file..."
          cat > "${{ inputs.ignore-file }}" <<EOF
        node_modules/
        dist/
        build/
        coverage/
        .git/
        *.min.js
        *.d.ts
        EOF
        fi

    - name: Run Prettier Check
      id: check
      shell: bash
      run: |
        set -euo pipefail

        cd ${{ inputs.working-directory }}

        # Create reports directory
        mkdir -p reports

        # Function to convert Prettier output to SARIF
        prettier_to_sarif() {
          local input_file=$1
          local output_file=$2

          echo '{
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "Prettier",
                    "informationUri": "https://prettier.io",
                    "rules": []
                  }
                },
                "results": [' > "$output_file"

          local first=true
          while IFS= read -r line; do
            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> "$output_file"
            fi

            echo "{
              \"level\": \"error\",
              \"message\": {
                \"text\": \"File is not formatted according to Prettier rules\"
              },
              \"locations\": [
                {
                  \"physicalLocation\": {
                    \"artifactLocation\": {
                      \"uri\": \"$line\"
                    }
                  }
                }
              ]
            }" >> "$output_file"
          done < "$input_file"

          echo ']}]}' >> "$output_file"
        }

        # Run Prettier
        echo "Running Prettier check..."
        unformatted_files=$(mktemp)

        if [ "${{ inputs.check-only }}" = "true" ]; then
          npx prettier \
            --check \
            --config "${{ inputs.config-file }}" \
            --ignore-path "${{ inputs.ignore-file }}" \
            ${{ inputs.cache == 'true' && '--cache --cache-location=.prettier-cache' || '' }} \
            --no-error-on-unmatched-pattern \
            "${{ inputs.file-pattern }}" 2>&1 | \
            grep -oE '[^ ]+\.[a-zA-Z]+$' > "$unformatted_files" || true
        else
          npx prettier \
            --write \
            --list-different \
            --config "${{ inputs.config-file }}" \
            --ignore-path "${{ inputs.ignore-file }}" \
            ${{ inputs.cache == 'true' && '--cache --cache-location=.prettier-cache' || '' }} \
            --no-error-on-unmatched-pattern \
            "${{ inputs.file-pattern }}" > "$unformatted_files" || true
        fi

        # Count files
        files_checked=$(find . -type f -name "${{ inputs.file-pattern }}" -not -path "*/node_modules/*" | wc -l)
        unformatted_count=$(wc -l < "$unformatted_files")

        echo "files_checked=${files_checked}" >> $GITHUB_OUTPUT
        echo "unformatted_files=${unformatted_count}" >> $GITHUB_OUTPUT

        # Generate SARIF report if requested
        if [ "${{ inputs.report-format }}" = "sarif" ]; then
          prettier_to_sarif "$unformatted_files" "reports/prettier.sarif"
          echo "sarif_file=reports/prettier.sarif" >> $GITHUB_OUTPUT
        fi

        # Clean up temporary file
        rm "$unformatted_files"

        # Exit with error if issues found and fail-on-error is true
        if [ "${{ inputs.fail-on-error }}" = "true" ] && [ "$unformatted_count" -gt 0 ]; then
          echo "::error::Found $unformatted_count files with formatting issues"
          exit 1
        fi

    - name: Upload Prettier Results
      if: always() && inputs.report-format == 'sarif'
      uses: github/codeql-action/upload-sarif@64d10c13136e1c5bce3e5fbde8d4906eeaafc885 # v3.30.6
      with:
        sarif_file: ${{ inputs.working-directory }}/reports/prettier.sarif
        category: prettier

    - name: Cleanup
      if: always()
      shell: bash
      run: |
        set -euo pipefail

        cd ${{ inputs.working-directory }}

        # Remove temporary files
        rm -rf reports/

        # Clean cache if exists and not being preserved
        if [ "${{ inputs.cache }}" != "true" ]; then
          rm -rf .prettier-cache
          rm -rf node_modules/.cache/prettier
        fi
