---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Prettier Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git Config
        uses: ivuorinen/actions/composite/set-git-config@main

      - name: Node Setup
        uses: ivuorinen/actions/composite/node-setup@main

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Prettier Check
        run: |
          npx prettier --check . --loglevel warn --write-report --report-output prettier-report.json

      - name: Upload Prettier Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: prettier-report.json
