# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
---
name: ESLint Fix
description: Fixes ESLint violations in a project.
author: 'Ismo Vuorinen'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for authentication'
    required: false
    default: ${{ github.token }}
  username:
    description: 'GitHub username for commits'
    required: false
    default: 'github-actions'
  email:
    description: 'GitHub email for commits'
    required: false
    default: 'github-actions@github.com'
  max-retries:
    description: 'Maximum number of retry attempts for npm install operations'
    required: false
    default: '3'

outputs:
  files_changed:
    description: 'Number of files changed by ESLint'
    value: ${{ steps.lint.outputs.files_changed }}
  lint_status:
    description: 'Linting status (success/failure)'
    value: ${{ steps.lint.outputs.status }}
  errors_fixed:
    description: 'Number of errors fixed'
    value: ${{ steps.lint.outputs.errors_fixed }}

runs:
  using: composite
  steps:
    - name: Validate Inputs
      id: validate
      uses: ./validate-inputs
      with:
        action-type: 'eslint-fix'
        token: ${{ inputs.token }}
        email: ${{ inputs.email }}
        username: ${{ inputs.username }}
        max-retries: ${{ inputs.max-retries }}

    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        token: ${{ inputs.token }}

    - name: Set Git Config
      uses: ./set-git-config
      with:
        token: ${{ inputs.token }}
        username: ${{ inputs.username }}
        email: ${{ inputs.email }}

    - name: Node Setup
      id: node-setup
      uses: ./node-setup

    - name: Cache Node Dependencies
      id: cache
      uses: ./common-cache
      with:
        type: 'npm'
        paths: 'node_modules'
        key-files: 'package-lock.json,yarn.lock,pnpm-lock.yaml,bun.lockb'
        key-prefix: 'eslint-fix-${{ steps.node-setup.outputs.package-manager }}'

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail

        package_manager="${{ steps.node-setup.outputs.package-manager }}"
        max_retries="${{ inputs.max-retries }}"

        echo "Installing dependencies using $package_manager..."

        for attempt in $(seq 1 $max_retries); do
          echo "Attempt $attempt of $max_retries"

          case "$package_manager" in
            "pnpm")
              if pnpm install --frozen-lockfile; then
                echo "✅ Dependencies installed successfully with pnpm"
                exit 0
              fi
              ;;
            "yarn")
              if [ -f ".yarnrc.yml" ]; then
                if yarn install --immutable; then
                  echo "✅ Dependencies installed successfully with Yarn Berry"
                  exit 0
                fi
              else
                if yarn install --frozen-lockfile; then
                  echo "✅ Dependencies installed successfully with Yarn Classic"
                  exit 0
                fi
              fi
              ;;
            "bun")
              if bun install --frozen-lockfile; then
                echo "✅ Dependencies installed successfully with Bun"
                exit 0
              fi
              ;;
            "npm"|*)
              if npm ci; then
                echo "✅ Dependencies installed successfully with npm"
                exit 0
              fi
              ;;
          esac

          if [ $attempt -lt $max_retries ]; then
            echo "❌ Installation failed, retrying in 5 seconds..."
            sleep 5
          fi
        done

        echo "::error::Failed to install dependencies after $max_retries attempts"
        exit 1

    - name: Run ESLint Fix
      id: lint
      shell: bash
      run: |
        set -euo pipefail

        package_manager="${{ steps.node-setup.outputs.package-manager }}"

        echo "Running ESLint fix with $package_manager..."

        # Count files before fix
        files_before=$(git status --porcelain | wc -l || echo "0")

        # Run ESLint fix based on package manager
        case "$package_manager" in
          "pnpm")
            pnpm exec eslint . --fix || true
            ;;
          "yarn")
            yarn eslint . --fix || true
            ;;
          "bun")
            bunx eslint . --fix || true
            ;;
          "npm"|*)
            npx eslint . --fix || true
            ;;
        esac

        # Count files after fix
        files_after=$(git status --porcelain | wc -l || echo "0")
        files_changed=$((files_after - files_before))

        # Get number of staged changes
        errors_fixed=$(git diff --cached --numstat | wc -l || echo "0")

        echo "files_changed=$files_changed" >> $GITHUB_OUTPUT
        echo "errors_fixed=$errors_fixed" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT

        echo "✅ ESLint fix completed. Files changed: $files_changed, Errors fixed: $errors_fixed"

    - name: Push Fixes
      if: always()
      uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
      with:
        commit_message: 'style: autofix ESLint violations'
        add_options: '-u'
