---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: ESLint Fix
description: Fixes ESLint violations in a project.
author: 'Ismo Vuorinen'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for authentication'
    required: false
    default: ${{ github.token }}
  username:
    description: 'GitHub username for commits'
    required: false
    default: 'github-actions'
  email:
    description: 'GitHub email for commits'
    required: false
    default: 'github-actions@github.com'

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        token: ${{ inputs.token }}

    - name: Set Git Config
      uses: ivuorinen/actions/set-git-config@main
      with:
        token: ${{ inputs.token }}
        username: ${{ inputs.username }}
        email: ${{ inputs.email }}

    - name: Node Setup
      uses: ivuorinen/actions/node-setup@main

    - name: Install Dependencies
      shell: bash
      run: |
        set -euo pipefail

        npm install

    - name: Run ESLint Fix
      shell: bash
      run: |
        set -euo pipefail

        npx eslint . --fix

    - name: Push Fixes
      if: always()
      uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
      with:
        commit_message: 'style: autofix ESLint violations'
        add_options: '-u'
