---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: ESLint Fix

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  eslint-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git Config
        uses: ivuorinen/actions/composite-set-git-config@main

      - name: Node Setup
        uses: ivuorinen/actions/composite-node-setup@main

      - name: Install Dependencies
        shell: bash
        run: |
          npm install

      - name: Run ESLint Fix
        shell: bash
        run: |
          npx eslint . --fix

      - name: Push Fixes
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: autofix ESLint violations'
          add_options: '-u'
