# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# permissions:
#   - contents: write  # Required for pushing fixes back to repository
---
name: ESLint Fix
description: Fixes ESLint violations in a project.
author: 'Ismo Vuorinen'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for authentication'
    required: false
    default: ${{ github.token }}
  username:
    description: 'GitHub username for commits'
    required: false
    default: 'github-actions'
  email:
    description: 'GitHub email for commits'
    required: false
    default: 'github-actions@github.com'
  max-retries:
    description: 'Maximum number of retry attempts for npm install operations'
    required: false
    default: '3'

outputs:
  files_changed:
    description: 'Number of files changed by ESLint'
    value: ${{ steps.lint.outputs.files_changed }}
  lint_status:
    description: 'Linting status (success/failure)'
    value: ${{ steps.lint.outputs.status }}
  errors_fixed:
    description: 'Number of errors fixed'
    value: ${{ steps.lint.outputs.errors_fixed }}

runs:
  using: composite
  steps:
    - name: Validate Inputs
      id: validate
      uses: ivuorinen/actions/validate-inputs@0fa9a68f07a1260b321f814202658a6089a43d42
      with:
        action-type: 'eslint-fix'
        token: ${{ inputs.token }}
        email: ${{ inputs.email }}
        username: ${{ inputs.username }}
        max-retries: ${{ inputs.max-retries }}

    - name: Checkout Repository
      uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v6-beta
      with:
        token: ${{ inputs.token }}

    - name: Node Setup
      id: node-setup
      uses: ivuorinen/actions/node-setup@0fa9a68f07a1260b321f814202658a6089a43d42

    - name: Cache Node Dependencies
      id: cache
      uses: ivuorinen/actions/common-cache@0fa9a68f07a1260b321f814202658a6089a43d42
      with:
        type: 'npm'
        paths: 'node_modules'
        key-files: 'package-lock.json,yarn.lock,pnpm-lock.yaml,bun.lockb'
        key-prefix: 'eslint-fix-${{ steps.node-setup.outputs.package-manager }}'

    - name: Install Dependencies
      id: install-deps
      if: steps.cache.outputs.cache-hit != 'true'
      shell: sh
      env:
        PACKAGE_MANAGER: ${{ steps.node-setup.outputs.package-manager }}
      run: |
        set -eu

        echo "Installing dependencies using $PACKAGE_MANAGER..."

        # Package managers have built-in retry logic
        case "$PACKAGE_MANAGER" in
          "pnpm")
            pnpm install --frozen-lockfile
            ;;
          "yarn")
            if [ -f ".yarnrc.yml" ]; then
              yarn install --immutable
            else
              yarn install --frozen-lockfile
            fi
            ;;
          "bun")
            bun install --frozen-lockfile
            ;;
          "npm"|*)
            npm ci
            ;;
        esac

        echo "✅ Dependencies installed successfully"

    - name: Run ESLint Fix
      id: lint
      shell: sh
      env:
        PACKAGE_MANAGER: ${{ steps.node-setup.outputs.package-manager }}
      run: |
        set -eu

        echo "Running ESLint fix with $PACKAGE_MANAGER..."

        # Count files before fix
        files_before=$(git status --porcelain | wc -l || echo "0")

        # Run ESLint fix based on package manager
        case "$PACKAGE_MANAGER" in
          "pnpm")
            pnpm exec eslint . --fix || true
            ;;
          "yarn")
            yarn eslint . --fix || true
            ;;
          "bun")
            bunx eslint . --fix || true
            ;;
          "npm"|*)
            npx eslint . --fix || true
            ;;
        esac

        # Count files after fix
        files_after=$(git status --porcelain | wc -l || echo "0")
        files_changed=$((files_after - files_before))

        # Get number of staged changes
        errors_fixed=$(git diff --cached --numstat | wc -l || echo "0")

        printf '%s\n' "files_changed=$files_changed" >> "$GITHUB_OUTPUT"
        printf '%s\n' "errors_fixed=$errors_fixed" >> "$GITHUB_OUTPUT"
        printf '%s\n' "status=success" >> "$GITHUB_OUTPUT"

        echo "✅ ESLint fix completed. Files changed: $files_changed, Errors fixed: $errors_fixed"

    - name: Push Fixes
      if: always()
      uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
      with:
        commit_message: 'style: autofix ESLint violations'
        commit_user_name: ${{ inputs.username }}
        commit_user_email: ${{ inputs.email }}
        add_options: '-u'
