---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Python Lint and Fix

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      security-events: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint and Fix Python Files
        uses: ivuorinen/actions/composite-python-lint-fix@main
