---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Biome Check
description: Run Biome check on the repository
author: Ismo Vuorinen

branding:
  icon: check-circle
  color: green

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set Git Config
      uses: ivuorinen/actions/set-git-config@main

    - name: Node Setup
      uses: ivuorinen/actions/node-setup@main

    - name: Install Dependencies
      shell: bash
      run: |
        npm install -g biome

    - name: Run Biome Check
      shell: bash
      run: |
        biome check . --json > biome-report.json

    - name: Upload Biome Results
      uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11
      with:
        sarif_file: biome-report.json
