---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Biome Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  biome-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git Config
        uses: ivuorinen/actions/composite/set-git-config@main

      - name: Node Setup
        uses: ivuorinen/actions/composite/node-setup@main

      - name: Install Dependencies
        run: |
          npm install -g biome

      - name: Run Biome Check
        run: |
          biome check . --json > biome-report.json

      - name: Upload Biome Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: biome-report.json
