---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Biome Check
description: Run Biome check on the repository
author: Ismo Vuorinen

branding:
  icon: check-circle
  color: green

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set Git Config
      uses: ./set-git-config

    - name: Node Setup
      uses: ./node-setup

    - name: Install Dependencies
      shell: bash
      run: |
        npm install -g biome

    - name: Run Biome Check
      shell: bash
      run: |
        biome check . --json > biome-report.json

    - name: Upload Biome Results
      uses: github/codeql-action/upload-sarif@64d10c13136e1c5bce3e5fbde8d4906eeaafc885 # v3.30.6
      with:
        sarif_file: biome-report.json
