---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Biome Check
description: Run Biome check on the repository
author: Ismo Vuorinen

branding:
  icon: check-circle
  color: green

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set Git Config
      uses: ivuorinen/actions/set-git-config@main

    - name: Node Setup
      uses: ivuorinen/actions/node-setup@main

    - name: Install Dependencies
      shell: bash
      run: |
        npm install -g biome

    - name: Run Biome Check
      shell: bash
      run: |
        biome check . --json > biome-report.json

    - name: Upload Biome Results
      uses: github/codeql-action/upload-sarif@9e8d0789d4a0fa9ceb6b1738f7e269594bdd67f0 # v3.28.9
      with:
        sarif_file: biome-report.json
