---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Docker Publish to GitHub Packages
description: "Publishes a Docker image to GitHub Packages."
author: "Ismo Vuorinen"

branding:
  icon: "package"
  color: "blue"

inputs:
  image-name:
    description: "The name of the Docker image to publish. Defaults to the repository name."
    required: false
  tags:
    description: "Comma-separated list of tags for the Docker image."
    required: true

runs:
  using: composite

  steps:
    - name: Determine Image Name
      id: image-name
      shell: bash
      run: |
        if [ -z "${{ inputs.image-name }}" ]; then
          repo_name=$(basename $GITHUB_REPOSITORY)
          echo "image-name=$repo_name" >> $GITHUB_OUTPUT
        else
          echo "image-name=${{ inputs.image-name }}" >> $GITHUB_OUTPUT
        fi

    - name: Push Docker Image to GitHub Packages
      uses: docker/build-push-action@v4
      id: build
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.image-name }}:${{ inputs.tags }}

    - name: Output Image Digest
      shell: bash
      run: |
        echo "Image digest: ${{ steps.build.outputs.digest }}"
