---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: ESLint Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  eslint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git Config
        uses: ivuorinen/actions/composite-set-git-config@main

      - name: Node Setup
        uses: ivuorinen/actions/composite-node-setup@main

      - name: Install Dependencies
        run: |
          npm install

      - name: Run ESLint Check
        run: |
          npx eslint . -f json -o eslint-report.json

      - name: Upload ESLint Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-report.json
