---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Common Cache
description: |
  Adds caching support for workflows with user-defined cache keys and paths.

branding:
  icon: database
  color: orange

inputs:
  path:
    description: 'Path to cache.'
    required: true
  key:
    description: 'Primary cache key.'
    required: true
  restore-keys:
    description: 'Restore keys for cache.'
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
