# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
---
name: Sync labels
description: Sync labels from a YAML file to a GitHub repository
author: Ismo Vuorinen

branding:
  icon: tag
  color: blue

inputs:
  labels:
    description: 'Path to the labels YAML file'
    required: true
    default: 'labels.yml'
  token:
    description: 'GitHub token for authentication'
    required: false
    default: ${{ github.token }}

outputs:
  labels:
    description: 'Path to the labels YAML file'
    value: ${{ inputs.labels }}

runs:
  using: 'composite'
  steps:
    - name: Validate Inputs
      id: validate
      shell: bash
      run: |
        set -euo pipefail

        # Validate labels file path format
        if [[ "${{ inputs.labels }}" == *".."* ]] || [[ "${{ inputs.labels }}" == "/"* ]]; then
          echo "::error::Invalid labels file path: '${{ inputs.labels }}'. Path traversal not allowed"
          exit 1
        fi

        # Validate labels file extension
        if ! [[ "${{ inputs.labels }}" =~ \.(yml|yaml)$ ]]; then
          echo "::error::Invalid labels file extension: '${{ inputs.labels }}'. Expected .yml or .yaml file"
          exit 1
        fi

        # Validate token is provided (basic check)
        if [[ -z "${{ inputs.token }}" ]]; then
          echo "::error::GitHub token is required for label synchronization"
          exit 1
        fi

    - name: â¤µï¸ Download latest labels definitions
      shell: bash
      run: |
        set -euo pipefail

        curl -s --retry 5 \
          "https://raw.githubusercontent.com/ivuorinen/actions/main/sync-labels/labels.yml" \
          > ${{ inputs.labels }}

    - name: ðŸš€ Run Label Syncer
      uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        manifest: ${{ inputs.labels }}
