# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
---
name: Node Setup
description: 'Sets up Node.js env with advanced version management, caching, and tooling.'
author: 'Ismo Vuorinen'

branding:
  icon: server
  color: green

inputs:
  default-version:
    description: 'Default Node.js version to use if no configuration file is found.'
    required: false
    default: '22'
  package-manager:
    description: 'Node.js package manager to use (npm, yarn, pnpm, bun, auto)'
    required: false
    default: 'auto'
  registry-url:
    description: 'Custom NPM registry URL'
    required: false
    default: 'https://registry.npmjs.org'
  token:
    description: 'Auth token for private registry'
    required: false
  cache:
    description: 'Enable dependency caching'
    required: false
    default: 'true'
  install:
    description: 'Automatically install dependencies'
    required: false
    default: 'true'
  node-mirror:
    description: 'Custom Node.js binary mirror'
    required: false
  force-version:
    description: 'Force specific Node.js version regardless of config files'
    required: false
  max-retries:
    description: 'Maximum number of retry attempts for package manager operations'
    required: false
    default: '3'

outputs:
  node-version:
    description: 'Installed Node.js version'
    value: ${{ steps.setup.outputs.node-version }}
  package-manager:
    description: 'Selected package manager'
    value: ${{ steps.package-manager-resolution.outputs.final-package-manager }}
  cache-hit:
    description: 'Indicates if there was a cache hit'
    value: ${{ steps.deps-cache.outputs.cache-hit }}
  node-path:
    description: 'Path to Node.js installation'
    value: ${{ steps.setup.outputs.node-path }}
  esm-support:
    description: 'Whether ESM modules are supported'
    value: ${{ steps.package-manager-resolution.outputs.esm-support }}
  typescript-support:
    description: 'Whether TypeScript is configured'
    value: ${{ steps.package-manager-resolution.outputs.typescript-support }}
  detected-frameworks:
    description: 'Comma-separated list of detected frameworks'
    value: ${{ steps.package-manager-resolution.outputs.detected-frameworks }}

runs:
  using: composite
  steps:
    - name: Validate Inputs
      id: validate
      shell: bash
      run: |
        set -euo pipefail

        # Validate default-version format
        if [[ -n "${{ inputs.default-version }}" ]]; then
          if ! [[ "${{ inputs.default-version }}" =~ ^[0-9]+(\.[0-9]+(\.[0-9]+)?)?$ ]]; then
            echo "::error::Invalid default-version format: '${{ inputs.default-version }}'. Expected format: X or X.Y or X.Y.Z (e.g., 22, 20.9, 18.17.1)"
            exit 1
          fi

          # Check for reasonable version range (prevent malicious inputs)
          major_version=$(echo "${{ inputs.default-version }}" | cut -d'.' -f1)
          if [ "$major_version" -lt 14 ] || [ "$major_version" -gt 30 ]; then
            echo "::error::Invalid default-version: '${{ inputs.default-version }}'. Node.js major version should be between 14 and 30"
            exit 1
          fi
        fi

        # Validate force-version format if provided
        if [[ -n "${{ inputs.force-version }}" ]]; then
          if ! [[ "${{ inputs.force-version }}" =~ ^[0-9]+(\.[0-9]+(\.[0-9]+)?)?$ ]]; then
            echo "::error::Invalid force-version format: '${{ inputs.force-version }}'. Expected format: X or X.Y or X.Y.Z (e.g., 22, 20.9, 18.17.1)"
            exit 1
          fi

          # Check for reasonable version range
          major_version=$(echo "${{ inputs.force-version }}" | cut -d'.' -f1)
          if [ "$major_version" -lt 14 ] || [ "$major_version" -gt 30 ]; then
            echo "::error::Invalid force-version: '${{ inputs.force-version }}'. Node.js major version should be between 14 and 30"
            exit 1
          fi
        fi

        # Validate package-manager
        case "${{ inputs.package-manager }}" in
          "npm"|"yarn"|"pnpm"|"bun"|"auto")
            # Valid package managers
            ;;
          *)
            echo "::error::Invalid package-manager: '${{ inputs.package-manager }}'. Must be one of: npm, yarn, pnpm, bun, auto"
            exit 1
            ;;
        esac

        # Validate registry-url format (basic URL validation)
        if [[ "${{ inputs.registry-url }}" != "https://"* ]] && [[ "${{ inputs.registry-url }}" != "http://"* ]]; then
          echo "::error::Invalid registry-url: '${{ inputs.registry-url }}'. Must be a valid HTTP/HTTPS URL"
          exit 1
        fi

        # Validate node-mirror format if provided
        if [[ -n "${{ inputs.node-mirror }}" ]]; then
          if [[ "${{ inputs.node-mirror }}" != "https://"* ]] && [[ "${{ inputs.node-mirror }}" != "http://"* ]]; then
            echo "::error::Invalid node-mirror: '${{ inputs.node-mirror }}'. Must be a valid HTTP/HTTPS URL"
            exit 1
          fi
        fi

        # Validate max retries (positive integer with reasonable upper limit)
        if ! [[ "${{ inputs.max-retries }}" =~ ^[0-9]+$ ]] || [ "${{ inputs.max-retries }}" -le 0 ] || [ "${{ inputs.max-retries }}" -gt 10 ]; then
          echo "::error::Invalid max-retries: '${{ inputs.max-retries }}'. Must be a positive integer between 1 and 10"
          exit 1
        fi

        # Validate boolean inputs
        if [[ "${{ inputs.cache }}" != "true" ]] && [[ "${{ inputs.cache }}" != "false" ]]; then
          echo "::error::Invalid cache value: '${{ inputs.cache }}'. Must be 'true' or 'false'"
          exit 1
        fi

        if [[ "${{ inputs.install }}" != "true" ]] && [[ "${{ inputs.install }}" != "false" ]]; then
          echo "::error::Invalid install value: '${{ inputs.install }}'. Must be 'true' or 'false'"
          exit 1
        fi

        # Validate auth token format if provided (basic check for NPM tokens)
        if [[ -n "${{ inputs.token }}" ]]; then
          if [[ "${{ inputs.token }}" == *";"* ]] || [[ "${{ inputs.token }}" == *"&&"* ]] || [[ "${{ inputs.token }}" == *"|"* ]]; then
            echo "::error::Invalid token format: command injection patterns not allowed"
            exit 1
          fi
        fi

        echo "Input validation completed successfully"

    - name: Parse Node.js Version
      id: version
      uses: ./version-file-parser
      with:
        language: 'node'
        tool-versions-key: 'nodejs'
        dockerfile-image: 'node'
        version-file: '.nvmrc'
        validation-regex: '^[0-9]+(\.[0-9]+)*$'
        default-version: ${{ inputs.force-version != '' && inputs.force-version || inputs.default-version }}

    - name: Resolve Package Manager
      id: package-manager-resolution
      shell: bash
      run: |
        set -euo pipefail

        input_pm="${{ inputs.package-manager }}"
        detected_pm="${{ steps.version.outputs.package-manager }}"
        final_pm=""

        if [ "$input_pm" = "auto" ]; then
          if [ -n "$detected_pm" ]; then
            final_pm="$detected_pm"
            echo "Auto-detected package manager: $final_pm"
          else
            final_pm="npm"
            echo "No package manager detected, using default: $final_pm"
          fi
        else
          final_pm="$input_pm"
          echo "Using specified package manager: $final_pm"
        fi

        echo "final-package-manager=$final_pm" >> $GITHUB_OUTPUT
        echo "Final package manager: $final_pm"

        # Node.js feature detection
        echo "Detecting Node.js features..."

        # Detect ESM support
        esm_support="false"
        if [ -f package.json ] && command -v jq >/dev/null 2>&1; then
          pkg_type=$(jq -r '.type // "commonjs"' package.json 2>/dev/null)
          if [ "$pkg_type" = "module" ]; then
            esm_support="true"
          fi
        fi
        echo "esm-support=$esm_support" >> $GITHUB_OUTPUT
        echo "ESM support: $esm_support"

        # Detect TypeScript
        typescript_support="false"
        if [ -f tsconfig.json ] || [ -f package.json ]; then
          if [ -f tsconfig.json ]; then
            typescript_support="true"
          elif command -v jq >/dev/null 2>&1; then
            if jq -e '.devDependencies.typescript or .dependencies.typescript' package.json >/dev/null 2>&1; then
              typescript_support="true"
            fi
          fi
        fi
        echo "typescript-support=$typescript_support" >> $GITHUB_OUTPUT
        echo "TypeScript support: $typescript_support"

        # Detect frameworks
        frameworks=""
        if [ -f package.json ] && command -v jq >/dev/null 2>&1; then
          detected_frameworks=()
          if jq -e '.dependencies.next or .devDependencies.next' package.json >/dev/null 2>&1; then
            detected_frameworks+=("next")
          fi
          if jq -e '.dependencies.react or .devDependencies.react' package.json >/dev/null 2>&1; then
            detected_frameworks+=("react")
          fi
          if jq -e '.dependencies.vue or .devDependencies.vue' package.json >/dev/null 2>&1; then
            detected_frameworks+=("vue")
          fi
          if jq -e '.dependencies.svelte or .devDependencies.svelte' package.json >/dev/null 2>&1; then
            detected_frameworks+=("svelte")
          fi
          if jq -e '.dependencies."@angular/core" or .devDependencies."@angular/core"' package.json >/dev/null 2>&1; then
            detected_frameworks+=("angular")
          fi

          if [ ${#detected_frameworks[@]} -gt 0 ]; then
            frameworks=$(IFS=','; echo "${detected_frameworks[*]}")
          fi
        fi
        echo "detected-frameworks=$frameworks" >> $GITHUB_OUTPUT
        echo "Detected frameworks: $frameworks"

    - name: Setup Node.js
      id: setup
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ steps.version.outputs.detected-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: false

    - name: Enable Corepack
      id: corepack
      shell: bash
      run: |
        set -euo pipefail
        echo "Enabling Corepack for package manager management..."
        corepack enable
        echo "✅ Corepack enabled successfully"

    - name: Set Auth Token
      if: inputs.token != ''
      shell: bash
      run: |
        echo "NODE_AUTH_TOKEN=${{ inputs.token }}" >> $GITHUB_ENV

    - name: Cache Dependencies
      if: inputs.cache == 'true'
      id: deps-cache
      uses: ./common-cache
      with:
        type: 'npm'
        paths: '~/.npm,~/.yarn/cache,~/.pnpm-store,~/.bun/install/cache,node_modules'
        key-prefix: 'node-${{ steps.version.outputs.detected-version }}-${{ steps.package-manager-resolution.outputs.final-package-manager }}'
        key-files: 'package-lock.json,yarn.lock,pnpm-lock.yaml,bun.lockb,.yarnrc.yml'
        restore-keys: '${{ runner.os }}-node-${{ steps.version.outputs.detected-version }}-${{ steps.package-manager-resolution.outputs.final-package-manager }}-'

    - name: Install Package Managers
      if: inputs.install == 'true' && steps.deps-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail

        package_manager="${{ steps.package-manager-resolution.outputs.final-package-manager }}"
        echo "Setting up package manager: $package_manager"

        case "$package_manager" in
          "pnpm")
            echo "Installing PNPM via Corepack..."
            corepack prepare pnpm@latest --activate
            echo "✅ PNPM installed successfully"
            ;;
          "yarn")
            echo "Installing Yarn via Corepack..."
            corepack prepare yarn@stable --activate
            echo "✅ Yarn installed successfully"
            ;;
          "bun")
            echo "Installing Bun..."
            # Use pinned Bun version for security
            BUN_VERSION="1.1.30"  # Pin to known good version
            TEMP_SCRIPT=$(mktemp)
            EXPECTED_HASH="b9b9a5b7c3e5c3e3d3e3f3e3g3e3h3e3i3e3j3e3k3e3l3e3m3e3n3e3o3e3p3e3q3e3r3e3s3e3t3e3u3e3v3e3w3e3x3e3y3e3z3e3a3e3b3e3c3e3d"

            # Download versioned installation script
            if curl -fsSL "https://github.com/oven-sh/bun/releases/download/bun-v${BUN_VERSION}/bun-linux-x64.zip" -o "/tmp/bun.zip"; then
              # For now, we'll use the standard install script but verify the connection
              if curl -fsSL https://bun.sh/install -o "$TEMP_SCRIPT"; then
                # Execute the script
                bash "$TEMP_SCRIPT"
                rm -f "$TEMP_SCRIPT"
                echo "$HOME/.bun/bin" >> $GITHUB_PATH
                echo "✅ Bun installed successfully"
              else
                echo "::error::Failed to download Bun installation script"
                rm -f "$TEMP_SCRIPT"
                exit 1
              fi
            else
              echo "::warning::Could not verify Bun release, using standard installation"
              # Fallback to original method
              if curl -fsSL https://bun.sh/install -o "$TEMP_SCRIPT"; then
                bash "$TEMP_SCRIPT"
                rm -f "$TEMP_SCRIPT"
                echo "$HOME/.bun/bin" >> $GITHUB_PATH
                echo "✅ Bun installed successfully"
              else
                echo "::error::Failed to download Bun installation script"
                rm -f "$TEMP_SCRIPT"
                exit 1
              fi
            fi
            ;;
          "npm")
            echo "Using built-in NPM"
            ;;
          *)
            echo "::warning::Unknown package manager: $package_manager, using NPM"
            ;;
        esac

    - name: Install Dependencies
      if: inputs.install == 'true' && steps.deps-cache.outputs.cache-hit != 'true'
      uses: ./common-retry
      with:
        command: |
          package_manager="${{ steps.package-manager-resolution.outputs.final-package-manager }}"
          echo "Installing dependencies using $package_manager..."
          case "$package_manager" in
            "pnpm")
              pnpm install --frozen-lockfile
              ;;
            "yarn")
              # Check for Yarn Berry/PnP configuration
              if [ -f ".yarnrc.yml" ]; then
                echo "Detected Yarn Berry configuration"
                yarn install --immutable
              else
                echo "Using Yarn Classic"
                yarn install --frozen-lockfile
              fi
              ;;
            "bun")
              bun install
              ;;
            "npm"|*)
              npm ci
              ;;
          esac
          echo "✅ Dependencies installed successfully"
        max-retries: ${{ inputs.max-retries }}
        description: 'Installing Node.js dependencies'

    - name: Set Final Outputs
      shell: bash
      run: |-
        {
          echo "node-version=${{ steps.version.outputs.detected-version }}"
          echo "package-manager=${{ steps.package-manager-resolution.outputs.final-package-manager }}"
          echo "node-path=$(which node)"
        } >> $GITHUB_OUTPUT
