---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Docker Publish to Docker Hub
description: 'Publishes a Docker image to Docker Hub.'
author: 'Ismo Vuorinen'

inputs:
  image-name:
    description: 'The name of the Docker image to publish. Defaults to the repository name.'
    required: false
  tags:
    description: 'Comma-separated list of tags for the Docker image.'
    required: true

runs:
  using: composite

  steps:
    - name: Determine Image Name
      id: image-name
      shell: bash
      run: |
        if [ -z "${{ inputs.image-name }}" ]; then
          repo_name=$(basename $GITHUB_REPOSITORY)
          echo "image-name=$repo_name" >> $GITHUB_OUTPUT
        else
          echo "image-name=${{ inputs.image-name }}" >> $GITHUB_OUTPUT
        fi

    - name: Docker Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: '${{ secrets.DOCKERHUB_USER }}'
        password: '${{ secrets.DOCKERHUB_PASS }}'

    - name: Push Docker Image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{ steps.image-name.outputs.image-name }}:${{ inputs.tags }}
