---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terraform Lint and Fix

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint and Fix Terraform Files
        uses: ivuorinen/actions/composite/terraform-lint-fix@main
