# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# permissions:
#   - contents: write  # Required for git configuration and operations
---
name: Set Git Config
description: 'Sets Git configuration for actions.'
author: 'Ismo Vuorinen'

branding:
  icon: git-commit
  color: gray-dark

inputs:
  token:
    description: 'GitHub token for authentication'
    required: false
    default: ${{ github.token }}
  username:
    description: 'GitHub username for commits.'
    default: 'github-actions'
  email:
    description: 'GitHub email for commits.'
    default: 'github-actions@github.com'
  is_fiximus:
    description: 'Whether to use the Fiximus bot.'
    required: false
    default: 'false'

outputs:
  token:
    description: 'GitHub token.'
    value: ${{ steps.bot.outputs.token }}
  username:
    description: 'GitHub username for commits.'
    value: ${{ steps.bot.outputs.username }}
  email:
    description: 'GitHub email for commits.'
    value: ${{ steps.bot.outputs.email }}
  is_fiximus:
    description: 'Whether to use the Fiximus bot.'
    value: ${{ steps.bot.outputs.is_fiximus }}

runs:
  using: composite
  steps:
    - name: Check for FIXIMUS_TOKEN
      id: bot
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        USERNAME: ${{ inputs.username }}
        EMAIL: ${{ inputs.email }}
        IS_FIXIMUS: ${{ inputs.is_fiximus }}
      run: |
        set -euo pipefail

        echo "token=$GITHUB_TOKEN" >> $GITHUB_OUTPUT
        echo "username=$USERNAME" >> $GITHUB_OUTPUT
        echo "email=$EMAIL" >> $GITHUB_OUTPUT

        if [ "$IS_FIXIMUS" != "false" ]; then
          echo "username=fiximus" >> $GITHUB_OUTPUT
          echo "email=github-bot@ivuorinen.net" >> $GITHUB_OUTPUT
        fi

    - name: Configure Git
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
        GIT_USERNAME: ${{ steps.bot.outputs.username }}
        GIT_EMAIL: ${{ steps.bot.outputs.email }}
      run: |-
        set -euo pipefail

        # Function to clean up Git config
        cleanup_git_config() {
          git config --local --unset-all "url.https://x-access-token:${TOKEN}@github.com/.insteadof" || true
          git config --local --unset-all "user.name" || true
          git config --local --unset-all "user.email" || true
        }

        # Set up trap to ensure cleanup on exit
        trap cleanup_git_config EXIT

        # Store token in variable to avoid repeated exposure
        TOKEN="$GITHUB_TOKEN"

        git config --local --unset-all http.https://github.com/.extraheader || true
        git config --local \
          --add url.https://x-access-token:${TOKEN}@github.com/.insteadOf \
          "https://github.com/"
        git config --local \
          --add url.https://x-access-token:${TOKEN}@github.com/.insteadOf \
          'git@github.com:'
        git config --local user.name "$GIT_USERNAME"
        git config --local user.email "$GIT_EMAIL"
