---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Setup Test Environment
description: Common setup for test jobs (Python, Node, system tools, ShellSpec)

inputs:
  install-act:
    description: Whether to install act for integration tests
    required: false
    default: 'false'
  install-kcov:
    description: Whether to install kcov for coverage
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@eb1897b8dc4b5d5bfe39a428a8f2304605e0983c # v7.0.0
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version-file: pyproject.toml

    - name: Install Python dependencies
      shell: bash
      run: uv sync --frozen

    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: '20'
        cache: npm

    - name: Install Node dependencies
      shell: bash
      run: npm ci

    - name: Install system tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends jq shellcheck
        if [[ "${{ inputs.install-kcov }}" == "true" ]]; then
          sudo apt-get install -y --no-install-recommends kcov || true
        fi

    - name: Install ShellSpec
      shell: bash
      run: |
        curl -fsSL https://git.io/shellspec | sh -s -- --yes
        sudo ln -s ~/.local/lib/shellspec/shellspec /usr/local/bin/shellspec

    - name: Install act
      if: inputs.install-act == 'true'
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash -s -- -b /usr/local/bin

    - name: Setup Docker and act configuration
      if: inputs.install-act == 'true'
      shell: bash
      run: |
        # Ensure Docker is running
        docker ps > /dev/null 2>&1 || (echo "Docker is not running" && exit 1)

        # Pre-pull the act Docker image to avoid interactive prompts
        docker pull catthehacker/ubuntu:act-latest

    - name: Verify tools
      shell: bash
      run: |
        shellspec --version
        jq --version
        uv --version
        if [[ "${{ inputs.install-act }}" == "true" ]]; then
          act --version
          docker --version
        fi
        if [[ "${{ inputs.install-kcov }}" == "true" ]]; then
          kcov --version || echo "kcov not available"
        fi
