---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git Config
        uses: ivuorinen/actions/composite-set-git-config@main

      - name: Build Go Project
        uses: ivuorinen/actions/composite-go-build@main

      - name: Run Tests
        run: |
          go test ./...
