---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: PHP Version Detect
description: "Detects the PHP version from the project's composer.json, phpunit.xml, or other configuration files."
author: 'Ismo Vuorinen'

branding:
  icon: code
  color: purple

inputs:
  default-version:
    description: 'Default PHP version to use if no version is detected.'
    required: false
    default: '8.2'

outputs:
  php-version:
    description: 'Detected or default PHP version.'
    value: ${{ steps.parse-version.outputs.detected-version }}

runs:
  using: composite
  steps:
    - name: Parse PHP Version
      id: parse-version
      uses: ivuorinen/actions/version-file-parser@main
      with:
        language: 'php'
        tool-versions-key: 'php'
        dockerfile-image: 'php'
        version-file: '.php-version'
        validation-regex: '^[0-9]+\.[0-9]+(\.[0-9]+)?$'
        default-version: ${{ inputs.default-version }}
