---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Ansible Lint and Fix
description: 'Lints and fixes Ansible playbooks, commits changes, and uploads SARIF report.'
author: 'Ismo Vuorinen'

branding:
  icon: 'play'
  color: 'green'

runs:
  using: composite
  steps:
    - name: Check for Ansible Files
      shell: bash
      run: |
        set -euo pipefail
        set -euo pipefail
        set -euo pipefail
        set -euo pipefail
        if ! find . -name "*.yml" | grep -q .; then
          echo "No Ansible files found. Skipping lint and fix."
          exit 0
        fi
        set -euo pipefail

    - name: Install ansible-lint
      shell: bash
      run: |
        set -euo pipefail
        set -euo pipefail
        set -euo pipefail
        set -euo pipefail
        pip install ansible-lint==6.22.1 || {
          echo "::error::Failed to install ansible-lint"
          exit 1
        }

    - name: Run ansible-lint
      shell: bash
        set -euo pipefail
      run: |
        set -euo pipefail
        set -euo pipefail
        set -euo pipefail
        set -euo pipefail
        ansible-lint --write --parseable-severity --format sarif > ansible-lint.sarif

    - name: Set Git Config for Fixes
      uses: ./set-git-config

    - name: Commit Fixes
      shell: bash
      run: |
        set -euo pipefail
        set -euo pipefail
        set -euo pipefail
        set -euo pipefail
        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add .
          git commit -m "fix: applied ansible lint fixes"
          git push
        fi

    - name: Upload SARIF Report
      uses: github/codeql-action/upload-sarif@4e828ff8d448a8a6e532957b1811f387a63867e8 # v3.29.4
      with:
        sarif_file: ansible-lint.sarif
