"""Tests for token validator.

Generated by generate-tests.py - Do not edit manually.
"""

from validators.token import TokenValidator


class TestTokenValidator:
    """Test cases for TokenValidator."""

    def setup_method(self):
        """Set up test fixtures."""
        self.validator = TokenValidator("test-action")

    def teardown_method(self):
        """Clean up after tests."""
        self.validator.clear_errors()

    def test_valid_github_token(self):
        """Test valid GitHub tokens."""
        # Classic PAT (4 + 36 chars)
        assert self.validator.validate_github_token("ghp_" + "a" * 36) is True
        # Fine-grained PAT (82 chars)
        assert self.validator.validate_github_token("github_pat_" + "a" * 71) is True
        # GitHub expression
        assert self.validator.validate_github_token("${{ secrets.GITHUB_TOKEN }}") is True

    def test_invalid_github_token(self):
        """Test invalid GitHub tokens."""
        assert self.validator.validate_github_token("invalid") is False
        assert self.validator.validate_github_token("ghp_short") is False
        assert self.validator.validate_github_token("", required=True) is False

    def test_ghs_stateful_token(self):
        """Stateful installation token: ghs_ + 36 alphanumeric (40 chars total)."""
        assert self.validator.validate_github_token("ghs_" + "a" * 36) is True
        assert self.validator.validate_github_token("ghs_" + "A1B2c3" * 6) is True

    def test_ghs_stateless_jwt_token(self):
        """Stateless installation token: ghs_APPID_JWT format with dots and underscores.

        Per GitHub (2026-04-27 rollout), installation tokens may now be ~520-char JWTs
        with two dots. The validator must accept both formats.
        """
        # Realistic stateless token: ghs_<APPID>_<header>.<payload>.<signature>
        jwt_header = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9"
        jwt_payload = "a" * 200
        jwt_signature = "b" * 256
        stateless = f"ghs_1234567_{jwt_header}.{jwt_payload}.{jwt_signature}"
        assert self.validator.validate_github_token(stateless) is True
        # Minimum stateless: ghs_ + 36 body chars including underscores and dots
        assert self.validator.validate_github_token("ghs_1_" + "x" * 30 + ".y.z") is True

    def test_ghs_stateless_rejects_invalid_chars(self):
        """ghs_ pattern allows only [A-Za-z0-9._] after the prefix."""
        # Plus sign — base64 standard, not base64url; not in GitHub's recommended regex
        assert self.validator.validate_github_token("ghs_" + "a" * 35 + "+") is False
        # Slash — not allowed
        assert self.validator.validate_github_token("ghs_" + "a" * 35 + "/") is False
        # Space — never allowed in tokens
        assert self.validator.validate_github_token("ghs_" + "a" * 35 + " ") is False

    def test_ghs_too_short(self):
        """ghs_ rejects bodies shorter than 36 chars."""
        assert self.validator.validate_github_token("ghs_" + "a" * 35) is False
        assert self.validator.validate_github_token("ghs_short") is False

    def test_ghs_length_boundaries(self):
        """ghs_ body length must satisfy 36 <= len <= 1024 exactly."""
        # Exactly minimum — accepted
        assert self.validator.validate_github_token("ghs_" + "a" * 36) is True
        # One below minimum — rejected
        assert self.validator.validate_github_token("ghs_" + "a" * 35) is False
        # Exactly upper bound — accepted
        assert self.validator.validate_github_token("ghs_" + "a" * 1024) is True
        # One over upper bound — rejected
        assert self.validator.validate_github_token("ghs_" + "a" * 1025) is False

    def test_other_token_types(self):
        """Test other token types."""
        # NPM token
        assert self.validator.validate_npm_token("npm_" + "a" * 40) is True
