---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Python Version Detect V2
description: 'Detects Python version from project configuration files using shared utilities.'
author: 'Ismo Vuorinen'

branding:
  icon: code
  color: blue

inputs:
  default-version:
    description: 'Default Python version to use if no version is detected.'
    required: false
    default: '3.12'

outputs:
  python-version:
    description: 'Detected or default Python version.'
    value: ${{ steps.parse-version.outputs.detected-version }}
  package-manager:
    description: 'Detected Python package manager (pip, poetry, pipenv).'
    value: ${{ steps.parse-version.outputs.package-manager }}

runs:
  using: composite
  steps:
    - name: Parse Python Version
      id: parse-version
      uses: ivuorinen/actions/version-file-parser@main
      with:
        language: 'python'
        tool-versions-key: 'python'
        dockerfile-image: 'python'
        version-file: '.python-version'
        validation-regex: '^[0-9]+\.[0-9]+(\.[0-9]+)?$'
        default-version: ${{ inputs.default-version }}
