---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Docker Build
description: "Builds a Docker image for multiple architectures."
author: "Ismo Vuorinen"

branding:
  icon: "package"
  color: "blue"

inputs:
  image-name:
    description: "The name of the Docker image to build. Defaults to the repository name."
    required: false
  tag:
    description: "The tag for the Docker image."
    required: true
  architectures:
    description: "List of architectures to build for. Defaults to amd64, arm64, arm/v7, arm/v6."
    required: false
    default: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"

runs:
  using: composite

  steps:
    - name: Determine Image Name
      id: image-name
      shell: bash
      run: |
        if [ -z "${{ inputs.image-name }}" ]; then
          repo_name=$(basename "${GITHUB_REPOSITORY}")
          echo "image-name=$repo_name" >> $GITHUB_OUTPUT
        else
          # Validate image name format
          if [[ ! "${{ inputs.image-name }}" =~ ^[a-z0-9]+(?:[._-][a-z0-9]+)*$ ]]; then
            echo "Error: Invalid image name format"
            exit 1
          fi
          echo "image-name=${{ inputs.image-name }}" >> $GITHUB_OUTPUT
        fi

    - name: Clean Platforms Input
      id: clean-platforms
      shell: bash
      run: |
        platforms=$(echo "${{ inputs.architectures }}" | tr -d ' ')
        echo "cleaned-platforms=$platforms" >> $GITHUB_OUTPUT

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Multi-Architecture Docker Image
      shell: bash
      run: |
        docker buildx build \
          --platform=${{ steps.clean-platforms.outputs.cleaned-platforms }} \
          --tag ${{ steps.image-name.outputs.image-name }}:${{ inputs.tag }} \
          . --push
