---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: GitHub Release
description: 'Creates a GitHub release with a version and changelog.'
author: 'Ismo Vuorinen'

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  version:
    description: 'The version for the release.'
    required: true
  changelog:
    description: 'The changelog or description for the release.'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Validate Inputs
      id: validate
      shell: bash
      run: |
        set -euo pipefail

        # Validate version format (semantic versioning)
        if ! [[ "${{ inputs.version }}" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?(\+[a-zA-Z0-9.-]+)?$ ]]; then
          echo "::error::Invalid version format: '${{ inputs.version }}'. Expected semantic version (e.g., '1.2.3', 'v1.2.3-alpha', '1.2.3+build')"
          exit 1
        fi

        # Validate changelog content (if provided)
        if [[ -n "${{ inputs.changelog }}" ]] && [[ ${#inputs.changelog} -gt 10000 ]]; then
          echo "::warning::Changelog is very long (${#inputs.changelog} characters). Consider using shorter release notes."
        fi

        # Check if gh CLI is available
        if ! command -v gh >/dev/null 2>&1; then
          echo "::error::GitHub CLI (gh) is not available. Please ensure it's installed in the environment."
          exit 1
        fi

    - name: Create GitHub Release with Autogenerated Changelog
      if: ${{ inputs.changelog == '' }}
      shell: bash
      run: |
        set -euo pipefail

        gh release create ${{ inputs.version }} \
          --repo="${GITHUB_REPOSITORY}" \
          --title="${{ inputs.version }}" \
          --generate-notes

    - name: Create GitHub Release with Custom Changelog
      if: ${{ inputs.changelog != '' }}
      shell: bash
      run: |
        set -euo pipefail

        gh release create ${{ inputs.version }} \
          --repo="${GITHUB_REPOSITORY}" \
          --title="${{ inputs.version }}" \
          --notes="${{ inputs.changelog }}"
