---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Lint Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git Config
        uses: ivuorinen/actions/composite/set-git-config@main

      - name: Lint Go Code
        uses: ivuorinen/actions/composite/go-lint-check@main

      - name: Upload Lint Results
        if: success()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: golangci-lint-report.sarif
