---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
#
# Compress images on demand (workflow_dispatch), and at 11pm every Sunday (schedule).
# Open a Pull Request if any images can be compressed.
name: Compress Images
description: Compress images on demand (workflow_dispatch), and at 11pm every Sunday (schedule).
author: Ismo Vuorinen

branding:
  icon: image
  color: blue

runs:
  using: composite
  steps:
    - name: Set Git Config
      uses: ivuorinen/actions/set-git-config@main

    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Compress Images
      id: calibre
      uses: calibreapp/image-actions@main
      with:
        compressOnly: true
        githubToken: ${{ steps.set-git-config.outputs.token }}

    - name: Create New Pull Request If Needed
      if: steps.calibre.outputs.markdown != ''
      uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7
      with:
        title: Compressed Images Nightly
        branch-suffix: timestamp
        commit-message: Compressed Images
        body: ${{ steps.calibre.outputs.markdown }}
