---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
#
# Compress images on demand (workflow_dispatch), and at 11pm every Sunday (schedule).
# Open a Pull Request if any images can be compressed.
name: Compress Images
description: Compress images on demand (workflow_dispatch), and at 11pm every Sunday (schedule).
author: Ismo Vuorinen

branding:
  icon: image
  color: blue

runs:
  using: composite
  steps:
    - name: Set Git Config
      uses: ./set-git-config

    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Compress Images
      id: calibre
      uses: calibreapp/image-actions@737ceeaeed61e17b8d358358a303f1b8d177b779 # v1.1.0
      with:
        compressOnly: true
        githubToken: ${{ steps.set-git-config.outputs.token }}

    - name: Create New Pull Request If Needed
      if: steps.calibre.outputs.markdown != ''
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        title: Compressed Images Nightly
        branch-suffix: timestamp
        commit-message: Compressed Images
        body: ${{ steps.calibre.outputs.markdown }}
