---
name: Stale

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  stale:
    uses: ivuorinen/actions/stale@main
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: read
      statuses: read
