---
name: Stale

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  stale:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ivuorinen/.github/.github/workflows/stale.yml@main
